# .github/workflows/python-app.yml

name: Python application # The name of the workflow

on: [push, pull_request] # Specifies the events that trigger the workflow: push and pull request

jobs:
  build: # Defines the build job
    runs-on: ubuntu-latest # Specifies the type of runner (Ubuntu latest version)

    steps:
    - name: Checkout code # Step to checkout the code from the repository
      uses: actions/checkout@v2 # Uses the checkout action to pull the latest code

    - name: Set up Python # Step to set up Python environment
      uses: actions/setup-python@v2 # Uses the setup-python action
      with:
        python-version: 3.8 # Specifies the Python version to be used (3.8 in this case)

    - name: Install dependencies # Step to install necessary dependencies
      run: |
        python -m pip install --upgrade pip # Upgrades pip to the latest version
        pip install flake8 # Installs flake8 for linting

    - name: Lint code # Step to lint the code using flake8
      run: |
        flake8 . # Runs flake8 on the entire repository
        # You can specify directories or files if needed, e.g., flake8 calculator.py tests

    - name: Run tests # Step to run unit tests
      run: |
        python -m unittest discover tests # Discovers and runs all tests in the tests directory
